# -*- mode: python ; coding: utf-8 -*-
"""Spec para PyInstaller - Windows ejecutable."""

a = Analysis(
    ['src/luciotech/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'luciotech',
        'luciotech.app',
        'luciotech.config',
        'luciotech.main',
        'luciotech.database',
        'luciotech.database.connection',
        'luciotech.database.models',
        'luciotech.database.repositories',
        'luciotech.services',
        'luciotech.services.order_service',
        'luciotech.services.image_service',
        'luciotech.services.backup_service',
        'luciotech.ui',
        'luciotech.ui.main_window',
        'luciotech.ui.pages',
        'luciotech.ui.pages.orders_page',
        'luciotech.ui.pages.reception_page',
        'luciotech.ui.pages.reports_page',
        'luciotech.ui.dialogs',
        'luciotech.ui.dialogs.customer_dialog',
        'luciotech.ui.dialogs.order_view_dialog',
        'luciotech.ui.dialogs.settings_dialog',
        'luciotech.ui.widgets',
        'luciotech.ui.widgets.rich_text_edit',
        'luciotech.ui.widgets.photo_tab',
        'luciotech.ui.widgets.history_timeline',
        'luciotech.ui.widgets.budget_payments_tab',
        'luciotech.reports',
        'luciotech.reports.pdf_service',
        'luciotech.utils',
        'luciotech.utils.logging_config',
        'platformdirs',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'reportlab',
        'reportlab.lib',
        'reportlab.platypus',
        'reportlab.lib.pagesizes',
        'PIL',
        'Pillow',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='JL_Mantenimiento',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # Add icon path when available
)
